# Generated by Django 4.0.2 on 2022-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wideo',
            name='video',
            field=models.FileField(upload_to='Wideo', verbose_name='Wideo'),
        ),
    ]
